#! /bin/bash

TDIR=$(mktemp -d -t XXXXXX)
TESTDIR=$(dirname $0)

# ======================================================================

function on_exit
{
    rm -rf "$TDIR"
}

trap on_exit EXIT

function failed
{
    echo ERROR: "$@" FAILED >&2
    exit 1
}

trap failed ERR

# ======================================================================

# export LD_LIBRARY_PATH="${ACMACSD_ROOT}/lib:${LD_LIBRARY_PATH}"
cd "$TESTDIR"
for test_prog in ../dist/test-double-to-string ../dist/test-rjson ../dist/test-rjson2 ../dist/test-settings ../dist/test-argc-argv ../dist/test-string-split ../dist/test-date2; do
    if ! ${test_prog}; then
        failed ${test_prog}
    fi
done
