#! /bin/bash

# TDIR=$(mktemp -d -t XXXXXX)
TESTDIR=$(dirname $0)

# ======================================================================

# function on_exit
# {
#     rm -rf "$TDIR"
# }

# trap on_exit EXIT

function failed
{
    echo ERROR: "$@" FAILED >&2
    exit 1
}

trap failed ERR

# ======================================================================

# https://github.com/google/sanitizers/wiki/AddressSanitizerFlags
# export LD_LIBRARY_PATH="${ACMACSD_ROOT}/lib:${LD_LIBRARY_PATH}"
cd "$TESTDIR"
for test_prog in ../dist/test-color-modifier ../dist/test-time-series ./test-settings-v2.sh ./test-settings-v3.sh ../dist/test-double-to-string ../dist/test-rjson-v2 ../dist/test-rjson-v3 ../dist/test-settings-v1 ../dist/test-string-split ../dist/test-date2 ../dist/test-find-color ../dist/test-string-join; do
    echo $(basename ${test_prog})
    # if ! ASAN_OPTIONS=verbosity=0:check_initialization_order=0:detect_leaks=0:detect_stack_use_after_return=0:print_stats=0:strict_string_checks=0 ASAN_SYMBOLIZER_PATH=/usr/local/opt/llvm/bin/llvm-symbolizer ${test_prog}; then
    if ! ASAN_OPTIONS=help=0:verbosity=0:check_initialization_order=1:detect_leaks=1:detect_stack_use_after_return=1:print_stats=0:strict_string_checks=1 ${test_prog}; then
        failed ${test_prog}
    fi
done
