#! /bin/bash
source $(dirname $0)/__setup

for P in locationdb acmacs-chart hidb seqdb acmacs-draw acmacs-map-draw acmacs-tree-maker signature-page acmacs-whocc acmacs-webserver acmacs-api; do
    src_dir "$P"
    make -C "ACMACS_PACKAGE_DIR" clean
    make -C "$ACMACS_PACKAGE_DIR" -j$NPROC OPTIMIZATION=
done
