#! /bin/bash
source $(dirname $0)/__setup
src_dir mongo-cxx-driver
clone_or_pull "$EXTERN_PACKAGE_DIR" "https://github.com/mongodb/mongo-cxx-driver.git" --branch releases/stable --depth 1
# https://mongodb.github.io/mongo-cxx-driver/mongocxx-v3/installation/

export PKG_CONFIG_PATH="$BUILD_ROOT"/lib/pkgconfig
# MONGO_CXX_SRC="$SRC_DIR/mongo-cxx-driver"

cd "$EXTERN_PACKAGE_DIR"/build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$BUILD_ROOT" ..
# -DBSONCXX_POLY_USE_BOOST=1
# Only for MNMLSTC polyfill (default on Linux and macos
# make EP_mnmlstc_core
make -j$NPROC
make install
if [ "$(uname)" == "Darwin" ]; then
    cd "$BUILD_ROOT/lib"
    rm -f *.a
    for library in libbsoncxx._noabi.dylib libmongocxx._noabi.dylib; do
        /usr/bin/install_name_tool -id "$BUILD_ROOT/lib/$library" "$library"
    done
    /usr/bin/install_name_tool -change "@rpath/libbsoncxx._noabi.dylib" "$BUILD_ROOT/lib/libbsoncxx._noabi.dylib" "libmongocxx._noabi.dylib"
fi
