#! /bin/bash
source $(dirname $0)/__setup
src_dir pybind11
clone_or_pull "$EXTERN_PACKAGE_DIR" "https://github.com/pybind/pybind11.git"
( cd "$BUILD_ROOT/include" && ln -sf "$EXTERN_PACKAGE_DIR"/include/* . )
