#! /bin/bash
source $(dirname $0)/__setup
src_dir rapidjson
clone_or_pull "$EXTERN_PACKAGE_DIR" "https://github.com/miloyip/rapidjson"
( cd "$BUILD_ROOT/include" && ln -sf "$EXTERN_PACKAGE_DIR"/include/* . )
